name: Equicord Builder

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  equicord-setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    outputs:
      ven_hash: ${{ steps.hash.outputs.hash }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix rsync

      - name: Setup Equicord build
        run: python3 src/equicord_setup.py

      - name: Modify .gitignore for dist and executables
        run: |
          cd Equicord
          if [ -f ".gitignore" ]; then
            sed -i -e '/dist/d' -e '/\.exe/d' -e '/equicord_installer/d' .gitignore
            echo "# Dist and executable files are intentionally tracked in this fork" >> .gitignore
          else
            echo "No .gitignore file found"
          fi

      - name: Install dependencies
        run: |
          cd Equicord
          npm i -g pnpm
          pnpm i --no-frozen-lockfile # WARN: --no-frozen-lockfile is very important, do not erase from command.

      - name: Update plugin
        run: |
          cd Equicord/src/plugins
          if [ -d "fakeProfile" ]; then
            rm -rf fakeProfile
          fi
          git clone --depth 1 https://github.com/gujarathisampath/fakeProfile.git
          rm -rf fakeProfile/.git
          find fakeProfile -type f -exec dos2unix {} +

      - name: Generate Equicord hash
        id: hash
        run: |
          cd Equicord
          echo "hash=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Upload Equicord artifact
        uses: actions/upload-artifact@v4
        with:
          name: equicord-setup
          path: Equicord
          retention-days: 1

  equicord-build:
    needs: equicord-setup
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Download Equicord artifact
        uses: actions/download-artifact@v4
        with:
          name: equicord-setup
          path: Equicord

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd Equicord
          npm i -g pnpm
          pnpm i --no-frozen-lockfile

      - name: Build artifacts
        shell: bash
        run: |
          cd Equicord
          
          git init -q
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -q -m "Temporary commit for build"
          
          git remote add origin https://github.com/Equicord/Equicord.git
          
          pnpm build
          pnpm buildWeb
          
          if [ "$RUNNER_OS" == "Windows" ]; then
            cmd.exe /c "rmdir /s /q .git"
          else
            rm -rf .git
          fi

          mv dist dist-${{ runner.os }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ runner.os }}
          path: Equicord/dist-*
          retention-days: 1

  combine-and-commit:
    needs: [equicord-setup, equicord-build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PAT }}
          path: 'main-repo'
          fetch-depth: 0
          submodules: false
          set-safe-directory: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Download Equicord artifact
        uses: actions/download-artifact@v4
        with:
          name: equicord-setup
          path: Equicord

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-artifacts

      - name: Combine artifacts
        run: |
          cd main-repo
          mkdir -p Equicord/dist

          for os_dir in dist-artifacts/dist-*; do
            if [ -d "$os_dir" ]; then
              os_name=$(basename "$os_dir")
              mkdir -p "Equicord/dist/$os_name"
              cp -a "$os_dir"/* "Equicord/dist/$os_name/"
            fi
          done

          echo "Combined dist contents:"
          ls -la Equicord/dist

      - name: Builded Equicord commit
        run: |
          cd main-repo
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull "https://$GITHUB_ACTOR:${{ secrets.MY_PAT }}@github.com/segeyy/fP-Auto-Build.git" main

          if [ -d "Equicord/" ]; then
            echo "Equicord build folder in repository is already exists, passing."
          else
            git add Equicord
            git commit -m "🤖 feat(build/Equicord): Equicord build upload"
            git push "https://$GITHUB_ACTOR:${{ secrets.MY_PAT }}@github.com/segeyy/fP-Auto-Build.git" main
          fi

      - name: Commit Equicord changes
        run: |
          cd main-repo
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull "https://$GITHUB_ACTOR:${{ secrets.MY_PAT }}@github.com/segeyy/fP-Auto-Build.git" main

          git add Equicord
          if ! git diff-index --quiet HEAD -- Equicord; then
            git commit -m "🤖 feat(build/Equicord): Equicord artifacts $(date +'%Y-%m-%d %H:%M')"
            git push "https://$GITHUB_ACTOR:${{ secrets.MY_PAT }}@github.com/segeyy/fP-Auto-Build.git" main
          else
            echo "No changes in Equicord directory"
          fi

      - name: Generate tag Release
        run: python3 main-repo/src/tag_generator.py

      - name: Upload Release
        if: ${{ github.ref_name == 'main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
          tag: ${{ env.RELEASE_VERSION }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/}-${tag#v}" \
            --generate-notes